// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: create_template_build_assignment.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createTemplateBuildAssignment = `-- name: CreateTemplateBuildAssignment :execrows
WITH snapshot_gc_fence AS MATERIALIZED (
    SELECT pg_advisory_xact_lock_shared(hashtextextended('e2b:snapshot:global-roots', 0))
), active AS (
    SELECT env.id
    FROM "public"."envs" env
    CROSS JOIN snapshot_gc_fence
    WHERE env.id = $1 AND env.deleted_at IS NULL
    FOR SHARE
)
INSERT INTO "public"."env_build_assignments" (env_id, build_id, tag)
SELECT $1, $2, $3::text
WHERE EXISTS (SELECT 1 FROM active)
`

type CreateTemplateBuildAssignmentParams struct {
	TemplateID string
	BuildID    uuid.UUID
	Tag        string
}

// FOR SHARE serializes against a concurrent DeleteTemplate so a build can't be
// attached to a soft-deleted env. 0 rows affected means the template is gone.
func (q *Queries) CreateTemplateBuildAssignment(ctx context.Context, arg CreateTemplateBuildAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, createTemplateBuildAssignment, arg.TemplateID, arg.BuildID, arg.Tag)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
