// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: snapshot_gc.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimSnapshotGCJobs = `-- name: ClaimSnapshotGCJobs :many
WITH claimable AS (
    SELECT id
    FROM public.snapshot_gc_jobs
    WHERE not_before <= now()
      AND next_attempt_at <= now()
      AND (
        state IN ('pending', 'retry')
        OR (state = 'leased' AND lease_expires_at < now())
      )
    ORDER BY next_attempt_at, created_at
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
UPDATE public.snapshot_gc_jobs job
SET state = 'leased',
    lease_owner = $1,
    lease_expires_at = now() + $2::interval,
    updated_at = now()
FROM claimable
WHERE job.id = claimable.id
RETURNING job.id, job.snapshot_env_id, job.sandbox_id, job.successor_build_id, job.candidate_build_id, job.state, job.not_before, job.next_attempt_at, job.attempts, job.lease_owner, job.lease_expires_at, job.last_error, job.created_at, job.updated_at, job.completed_at
`

type ClaimSnapshotGCJobsParams struct {
	LeaseOwner    *string
	LeaseDuration pgtype.Interval
	BatchSize     int32
}

func (q *Queries) ClaimSnapshotGCJobs(ctx context.Context, arg ClaimSnapshotGCJobsParams) ([]SnapshotGcJob, error) {
	rows, err := q.db.Query(ctx, claimSnapshotGCJobs, arg.LeaseOwner, arg.LeaseDuration, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotGcJob
	for rows.Next() {
		var i SnapshotGcJob
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotEnvID,
			&i.SandboxID,
			&i.SuccessorBuildID,
			&i.CandidateBuildID,
			&i.State,
			&i.NotBefore,
			&i.NextAttemptAt,
			&i.Attempts,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeSnapshotGCJob = `-- name: CompleteSnapshotGCJob :execrows
UPDATE public.snapshot_gc_jobs
SET state = 'done', lease_owner = NULL, lease_expires_at = NULL,
    last_error = NULL, completed_at = now(), updated_at = now()
WHERE id = $1 AND state = 'leased' AND lease_owner = $2
`

type CompleteSnapshotGCJobParams struct {
	ID         uuid.UUID
	LeaseOwner *string
}

func (q *Queries) CompleteSnapshotGCJob(ctx context.Context, arg CompleteSnapshotGCJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeSnapshotGCJob, arg.ID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countPendingSnapshotGCJobs = `-- name: CountPendingSnapshotGCJobs :one
SELECT count(*)::bigint
FROM public.snapshot_gc_jobs
WHERE state IN ('pending', 'retry', 'leased')
`

func (q *Queries) CountPendingSnapshotGCJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingSnapshotGCJobs)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deferSnapshotGCJob = `-- name: DeferSnapshotGCJob :execrows
UPDATE public.snapshot_gc_jobs
SET state = 'retry', next_attempt_at = $1,
    lease_owner = NULL, lease_expires_at = NULL,
    last_error = left($2, 4000), updated_at = now()
WHERE id = $3 AND state = 'leased' AND lease_owner = $4
`

type DeferSnapshotGCJobParams struct {
	NextAttemptAt time.Time
	LastError     string
	ID            uuid.UUID
	LeaseOwner    *string
}

func (q *Queries) DeferSnapshotGCJob(ctx context.Context, arg DeferSnapshotGCJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, deferSnapshotGCJob,
		arg.NextAttemptAt,
		arg.LastError,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueSupersededSnapshotGCJobs = `-- name: EnqueueSupersededSnapshotGCJobs :execrows
WITH current_assignment AS (
    SELECT eba.env_id, eba.created_at
    FROM public.env_build_assignments eba
    JOIN public.env_builds eb ON eb.id = eba.build_id
    WHERE eba.env_id = $3
      AND eba.build_id = $1
      AND eba.tag = 'default'
      AND eb.status_group = 'ready'
), current_tip AS (
    SELECT eba.build_id
    FROM public.env_build_assignments eba
    JOIN public.env_builds eb ON eb.id = eba.build_id
    WHERE eba.env_id = $3
      AND eba.tag = 'default'
      AND eb.status_group = 'ready'
    ORDER BY eba.created_at DESC, eba.build_id DESC
    LIMIT 1
)
INSERT INTO public.snapshot_gc_jobs (
    snapshot_env_id, sandbox_id, successor_build_id, candidate_build_id,
    not_before, next_attempt_at
)
SELECT s.env_id, s.sandbox_id, $1, old.build_id,
       now() + $2::interval, now() + $2::interval
FROM public.snapshots s
JOIN current_assignment current ON current.env_id = s.env_id
JOIN current_tip tip ON tip.build_id = $1
JOIN public.env_build_assignments old
  ON old.env_id = s.env_id
 AND old.tag = 'default'
 AND (old.created_at, old.build_id) < (current.created_at, $1)
JOIN public.env_builds old_build
  ON old_build.id = old.build_id
 AND old_build.status_group = 'ready'
WHERE s.env_id = $3
ON CONFLICT (snapshot_env_id, candidate_build_id) DO UPDATE
SET successor_build_id = EXCLUDED.successor_build_id,
    state = 'pending',
    not_before = EXCLUDED.not_before,
    next_attempt_at = EXCLUDED.next_attempt_at,
    attempts = 0,
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_error = NULL,
    completed_at = NULL,
    updated_at = now()
WHERE snapshot_gc_jobs.state = 'dead'
  AND snapshot_gc_jobs.successor_build_id IS DISTINCT FROM EXCLUDED.successor_build_id
`

type EnqueueSupersededSnapshotGCJobsParams struct {
	SuccessorBuildID *uuid.UUID
	GracePeriod      pgtype.Interval
	SnapshotEnvID    string
}

func (q *Queries) EnqueueSupersededSnapshotGCJobs(ctx context.Context, arg EnqueueSupersededSnapshotGCJobsParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueSupersededSnapshotGCJobs, arg.SuccessorBuildID, arg.GracePeriod, arg.SnapshotEnvID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hasInProgressSnapshotBuilds = `-- name: HasInProgressSnapshotBuilds :one
SELECT EXISTS (
    SELECT 1
    FROM public.env_build_assignments eba
    JOIN public.envs env ON env.id = eba.env_id AND env.source = 'snapshot'
    JOIN public.env_builds eb ON eb.id = eba.build_id
    WHERE eba.tag = 'default' AND eb.status_group = 'in_progress'
)::boolean
`

// An in-progress checkpoint has no final dependency header yet. Under the
// global advisory fence GC must defer until its reachability can be proven.
func (q *Queries) HasInProgressSnapshotBuilds(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasInProgressSnapshotBuilds)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listCurrentSnapshotGCHeads = `-- name: ListCurrentSnapshotGCHeads :many
SELECT DISTINCT ON (eba.env_id)
       eba.env_id,
       eba.build_id,
       COALESCE((s.config->>'filesystemOnly')::boolean, false)::boolean AS filesystem_only
FROM public.env_build_assignments eba
JOIN public.active_envs env ON env.id = eba.env_id
JOIN public.env_builds eb ON eb.id = eba.build_id AND eb.status_group = 'ready'
LEFT JOIN public.snapshots s ON s.env_id = eba.env_id
WHERE eba.tag = 'default'
ORDER BY eba.env_id, eba.created_at DESC, eba.build_id DESC
`

type ListCurrentSnapshotGCHeadsRow struct {
	EnvID          string
	BuildID        uuid.UUID
	FilesystemOnly bool
}

// Verify every active default-assignment head that shares this storage
// namespace. Template and snapshot-template heads can carry dependencies from
// a pause snapshot, so excluding them would make the reachability proof unsafe.
func (q *Queries) ListCurrentSnapshotGCHeads(ctx context.Context) ([]ListCurrentSnapshotGCHeadsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentSnapshotGCHeads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentSnapshotGCHeadsRow
	for rows.Next() {
		var i ListCurrentSnapshotGCHeadsRow
		if err := rows.Scan(&i.EnvID, &i.BuildID, &i.FilesystemOnly); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotGCProtectedBuilds = `-- name: ListSnapshotGCProtectedBuilds :many
WITH snapshot_tips AS (
    SELECT DISTINCT ON (eba.env_id) eba.build_id
    FROM public.env_build_assignments eba
    JOIN public.active_envs env ON env.id = eba.env_id AND env.source = 'snapshot'
    JOIN public.env_builds eb ON eb.id = eba.build_id AND eb.status_group = 'ready'
    WHERE eba.tag = 'default'
    ORDER BY eba.env_id, eba.created_at DESC, eba.build_id DESC
), assigned_template_builds AS (
    SELECT DISTINCT eba.build_id
    FROM public.env_build_assignments eba
    JOIN public.active_envs env ON env.id = eba.env_id AND env.source <> 'snapshot'
    JOIN public.env_builds eb ON eb.id = eba.build_id AND eb.status_group = 'ready'
)
SELECT build_id FROM snapshot_tips
UNION
SELECT build_id FROM assigned_template_builds
`

// Every currently-addressable non-snapshot assignment is a root. Snapshot
// environments retain only their newest ready default assignment as a root;
// older assignments are precisely the generations this queue may collect.
func (q *Queries) ListSnapshotGCProtectedBuilds(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSnapshotGCProtectedBuilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var build_id uuid.UUID
		if err := rows.Scan(&build_id); err != nil {
			return nil, err
		}
		items = append(items, build_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownsSnapshotGCLease = `-- name: OwnsSnapshotGCLease :one
SELECT EXISTS (
    SELECT 1
    FROM public.snapshot_gc_jobs
    WHERE id = $1
      AND state = 'leased'
      AND lease_owner = $2
      AND lease_expires_at > now()
)::boolean
`

type OwnsSnapshotGCLeaseParams struct {
	ID         uuid.UUID
	LeaseOwner *string
}

// Fence the irreversible storage mutation. A worker whose lease expired while
// waiting for the advisory lock must not delete after another worker reclaimed
// the same job.
func (q *Queries) OwnsSnapshotGCLease(ctx context.Context, arg OwnsSnapshotGCLeaseParams) (bool, error) {
	row := q.db.QueryRow(ctx, ownsSnapshotGCLease, arg.ID, arg.LeaseOwner)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const reconcileSnapshotGCJobs = `-- name: ReconcileSnapshotGCJobs :execrows
WITH missing AS (
    SELECT s.env_id AS snapshot_env_id,
           s.sandbox_id,
           CASE WHEN env.deleted_at IS NULL THEN tip.build_id ELSE NULL END::uuid AS successor_build_id,
           old.build_id AS candidate_build_id
    FROM public.snapshots s
    -- Include soft-deleted snapshot environments: their old GCS prefixes are
    -- still physical cleanup candidates even though they are no longer roots.
    JOIN public.envs env ON env.id = s.env_id
    JOIN LATERAL (
        SELECT eba.build_id, eba.created_at
        FROM public.env_build_assignments eba
        JOIN public.env_builds eb ON eb.id = eba.build_id AND eb.status_group = 'ready'
        WHERE eba.env_id = s.env_id AND eba.tag = 'default'
        ORDER BY eba.created_at DESC, eba.build_id DESC
        LIMIT 1
    ) tip ON TRUE
    JOIN public.env_build_assignments old
      ON old.env_id = s.env_id
     AND old.tag = 'default'
     AND (
       env.deleted_at IS NOT NULL
       OR (old.created_at, old.build_id) < (tip.created_at, tip.build_id)
     )
    JOIN public.env_builds old_build
      ON old_build.id = old.build_id
     AND old_build.status_group = 'ready'
    LEFT JOIN public.snapshot_gc_jobs job
      ON job.snapshot_env_id = s.env_id
     AND job.candidate_build_id = old.build_id
    WHERE job.id IS NULL
       OR (
         job.state = 'dead'
         AND job.successor_build_id IS DISTINCT FROM
           CASE WHEN env.deleted_at IS NULL THEN tip.build_id ELSE NULL END::uuid
       )
    ORDER BY old.created_at ASC, old.build_id ASC
    LIMIT $2
)
INSERT INTO public.snapshot_gc_jobs (
    snapshot_env_id, sandbox_id, successor_build_id, candidate_build_id,
    not_before, next_attempt_at
)
SELECT snapshot_env_id, sandbox_id, successor_build_id, candidate_build_id,
       now() + $1::interval, now() + $1::interval
FROM missing
ON CONFLICT (snapshot_env_id, candidate_build_id) DO UPDATE
SET successor_build_id = EXCLUDED.successor_build_id,
    state = 'pending',
    not_before = EXCLUDED.not_before,
    next_attempt_at = EXCLUDED.next_attempt_at,
    attempts = 0,
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_error = NULL,
    completed_at = NULL,
    updated_at = now()
WHERE snapshot_gc_jobs.state = 'dead'
  AND snapshot_gc_jobs.successor_build_id IS DISTINCT FROM EXCLUDED.successor_build_id
`

type ReconcileSnapshotGCJobsParams struct {
	GracePeriod pgtype.Interval
	BatchSize   int32
}

func (q *Queries) ReconcileSnapshotGCJobs(ctx context.Context, arg ReconcileSnapshotGCJobsParams) (int64, error) {
	result, err := q.db.Exec(ctx, reconcileSnapshotGCJobs, arg.GracePeriod, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewSnapshotGCLease = `-- name: RenewSnapshotGCLease :execrows
UPDATE public.snapshot_gc_jobs
SET lease_expires_at = now() + $1::interval,
    updated_at = now()
WHERE id = $2
  AND state = 'leased'
  AND lease_owner = $3
  AND lease_expires_at > now()
`

type RenewSnapshotGCLeaseParams struct {
	LeaseDuration pgtype.Interval
	ID            uuid.UUID
	LeaseOwner    *string
}

// The UPDATE both verifies ownership and keeps this row locked until the GC
// transaction commits. ClaimSnapshotGCJobs uses FOR UPDATE SKIP LOCKED, so no
// second worker can reclaim the job while the storage RPC is in flight.
func (q *Queries) RenewSnapshotGCLease(ctx context.Context, arg RenewSnapshotGCLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewSnapshotGCLease, arg.LeaseDuration, arg.ID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retrySnapshotGCJob = `-- name: RetrySnapshotGCJob :execrows
UPDATE public.snapshot_gc_jobs
SET attempts = attempts + 1,
    state = CASE WHEN attempts + 1 >= $1 THEN 'dead' ELSE 'retry' END,
    next_attempt_at = $2,
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_error = left($3, 4000),
    completed_at = CASE WHEN attempts + 1 >= $1 THEN now() ELSE NULL END,
    updated_at = now()
WHERE id = $4 AND state = 'leased' AND lease_owner = $5
`

type RetrySnapshotGCJobParams struct {
	MaxAttempts   int32
	NextAttemptAt time.Time
	LastError     string
	ID            uuid.UUID
	LeaseOwner    *string
}

func (q *Queries) RetrySnapshotGCJob(ctx context.Context, arg RetrySnapshotGCJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, retrySnapshotGCJob,
		arg.MaxAttempts,
		arg.NextAttemptAt,
		arg.LastError,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
